export const theme = {
  colors: {
    black: '#000',
    white: '#fff',
    text: '#2a2a2a',
    background: '#fff',
    primary: '#07c',
    secondary: '#05a',
    searchBlock: {
      color: '#6c757d',
      border: '#e0e0e0',
    },
    colorEmailNotification: '#f2f2f2',
    bgColorEmailNotification: '#0060af',
    bgColorNotification: '#e50000',
    transparent: 'transparent',
    secBgColorAsideBtn: '#3366ff',
    secBgColorHeaderBtn: 'rgba(51, 102, 255, 0.2)',
    secColorHeaderBtn: '#3366ff',
    bgcAside: 'rgba(51, 102, 255, 0.1)',
  },
  space: [0, 2, 4, 8, 16, 32, 64, 128, 256],
  fonts: {
    body: 'system-ui, sans-serif',
    heading: 'system-ui, sans-serif',
    monospace: 'Menlo, monospace',
  },
  fontSizes: {
    xs: '10px',
    s: '12px',
    m: '14px',
    l: '16px',
    xl: '64px',
  },
  fontWeights: {
    normal: 400,
    preBold: 600,
    bold: 700,
  },
  lineHeights: {
    aside: 1.5,
    heading: 1.125,
  },
  borders: {
    none: 'none',
    normal: '1px solid',
  },
  radii: {
    none: '0',
    sm: '4px',
    md: '6px',
    lg: '10px',
    round: '50%',
  },
};
